### ISSUE TITLE
Using GRPC via SSL leads to NoClassDefFoundError

### ISSUE THREAD

**Issue by fedinskiy** [vert-x3/vertx-grpc#102]
### Version

3.9.7

### Context

After updating vertx-grpc 3.9.6 to 3.9.7 an attempt to use grpc client to communicate with the server via ssl leads to this exception: `java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSLSessionCache` (full stacktrace can be seen here: https://gist.github.com/fedinskiy/04fd1658ab58516b5a2be24b8a378872)

### Do you have a reproducer?
* https://github.com/fedinskiy/reproducer/tree/grpc-ssl

### Steps to reproduce
Run test:
`mvn clean verify -Dvertx.version=3.9.7`

Result: test fails.

Expected result:
Test succeeds, same as running:
`mvn clean verify -Dvertx.version=3.9.6`

**Comment by akoniar** [comment]
@fedinskiy It's not bug. Remove the io.netty:netty-tcnative-boringssl-static dependecy from dependecy managment. After that the scenario from reproducer will work

**Comment by fedinskiy** [comment]
@akoniar it won't[1]

[1] https://gist.github.com/fedinskiy/a10f81c55f27248d3ad6d7dd5e184b35

**Comment by akoniar** [comment]
@fedinskiy add vertx-dependencies to the dependencies managment and remove tcnative version or set tcnative version to 2.0.36.Final

**Comment by fedinskiy** [comment]
@akoniar the second workaround works(but I suspect, that this change should be described somewhere, especially since we talk about a patch, and not a major version).
The first one is not, supposedly because boringssl is declared "test dependency"[1]
[1] https://github.com/vert-x3/vertx-dependencies/blob/master/pom.xml#L946

**Comment by akoniar** [comment]
@fedinskiy I took this version from https://repo.maven.apache.org/maven2/io/vertx/vertx-dependencies/3.9.7/vertx-dependencies-3.9.7.pom
So when you add vertex dependecies to the dep managment 
```
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.vertx</groupId>
        <artifactId>vertx-dependencies</artifactId>
        <version>${vertx.version}</version>
        <scope>import</scope>
      </dependency>
    </dependencies>
 </dependencyManagement>

```
and add tcnative dep 

```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <scope>compile</scope>
</dependency>
```
Then the reproducer works (for me) (BTW this is the supported use case)

On the other hand the vertx-grpc documentation should be improved. I missing information about setting up vertx-dependecies or netty-tcnative-boringssl-static version
